version: '3.3'

networks:
  full-stack1:

services:
  mysql-db:
    container_name: mysql-db
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      MSSQL_SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
     
    ports:
      - "1433:1433"
     
    volumes:
      - mysql-data:/var/opt/mssql
    networks:
      - full-stack1

  backend1:
    build:
      context: ./backend1
      dockerfile: Dockerfile  
     
    ports:
      - "8000:80"
    depends_on:
      - mysql-db
    networks:
      - full-stack1

  web:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend1
    networks:
      - full-stack1

volumes:
  mysql-data:
